import {useEffect,useRef,useState} from 'react';
import {createClient} from '@supabase/supabase-js';
const url=import.meta.env.VITE_SUPABASE_URL,key=import.meta.env.VITE_SUPABASE_ANON_KEY;
export const supabase=url&&key?createClient(url,key,{auth:{storage:window.localStorage,persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}}):null;
const money=v=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'}),number=v=>Number(v||0).toLocaleString('pt-BR');
const blankCarga={fornecedorId:'',produtoId:'',motoristaId:'',qtd:'',origem:'',destino:'',dataCarregamento:'',modalidadeFrete:'FOB',fretePorTon:'140',pallet:'',palletQuantidade:'',observacao:''};
const blankPedido={cargaId:'',fornecedorId:'',produtoId:'',qtd:'',origem:'',destino:'',modalidadeFrete:'FOB',pallet:'',palletQuantidade:'',email:'',whatsapp:'',condicao:'14 DIAS',precoCompra:'',observacao:''};
const blankVenda={clienteId:'',produtoId:'',vendedorId:'',qtd:'',precoUnitario:'',condicaoPagamento:'PIX',destino:'',obra:'',fretePorSaco:'0',pallet:'',palletQuantidade:'',observacao:''};
function pedidoText(x){return ['FORTE ATACAREJO — PEDIDO DE COMPRA '+x.numero,'FORNECEDOR: '+x.fornecedor,'PRODUTO: '+x.produto,'QUANTIDADE: '+number(x.qtd),'PREÇO DE COMPRA UNITÁRIO: '+money(x.precoCompra),'TOTAL: '+money(x.totalCompra),'CONDIÇÃO: '+x.condicao,'ORIGEM: '+x.origem,'DESTINO: '+x.destino,'FRETE: '+x.modalidadeFrete,'PALLETS: '+x.pallet+' • '+number(x.palletQuantidade),x.motorista?'MOTORISTA: '+x.motorista:'',x.observacao?'OBSERVAÇÕES: '+x.observacao:''].filter(Boolean).join('\n')}
function ContactLinks({pedido}){let phone=String(pedido.whatsapp||'').replace(/\D/g,'');if(phone.length===10||phone.length===11)phone='55'+phone;const text=pedidoText(pedido);return <div className="send-actions">{phone&&<a target="_blank" rel="noopener noreferrer" href={'https://wa.me/'+phone+'?text='+encodeURIComponent(text)}>ABRIR WHATSAPP</a>}{pedido.email&&<a href={'mailto:'+pedido.email+'?subject='+encodeURIComponent('Pedido '+pedido.numero+' — Forte Atacarejo')+'&body='+encodeURIComponent(text)}>ABRIR E-MAIL</a>}{!phone&&!pedido.email&&<small>Informe o contato do fornecedor no novo pedido para habilitar o envio.</small>}</div>}
const emptyData={cargas:[],compras:[],fornecedores:[],produtos:[],motoristasDisponiveis:[],motoristas:[],fretes:[],clientes:[],vendedores:[],vendas:[]};
function Select({label,items,value,onChange,description}){return <label>{label}<select required value={value} onChange={e=>onChange(e.target.value)}><option value="">SELECIONE…</option>{items.map(x=><option key={x.id} value={x.id}>{description?description(x):x.nome}</option>)}</select>{!items.length&&<small>Nenhum cadastro disponível. Cadastre ou aprove no Forte Vendas.</small>}</label>}
export default function App(){
 const [tab,setTab]=useState('VENDAS'),[data,setData]=useState(emptyData),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[carga,setCarga]=useState(blankCarga),[pedido,setPedido]=useState(blankPedido),[showTools,setShowTools]=useState(false),[venda,setVenda]=useState(blankVenda);
 const mounted=useRef(true);
 async function invoke(acao,extra={}){const r=await supabase.functions.invoke('mobile-carga-direta',{body:{acao,...extra}});if(r.error){let detail='Não foi possível concluir. Confira a conexão e tente novamente.';if(r.error.context instanceof Response){try{detail=(await r.error.context.clone().json()).error||detail;}catch{}}throw Error(detail)}return r.data;}
 async function listar(){setLoading(true);setError('');try{const r=await invoke('LISTAR');if(!r||!Array.isArray(r.cargas))throw Error('O painel retornou dados inválidos. Tente atualizar.');if(mounted.current)setData({...emptyData,...r});return r;}catch(e){if(mounted.current)setError(e.message);}finally{if(mounted.current)setLoading(false)}}
 useEffect(()=>{mounted.current=true;listar();return()=>{mounted.current=false}},[]);
 const patchVenda=(field,value)=>setVenda(x=>({...x,[field]:value}));
 const patch=(field,value)=>setCarga(x=>({...x,[field]:value})),patchPedido=(field,value)=>setPedido(x=>({...x,[field]:value}));
 const produto=data.produtos.find(x=>x.id===carga.produtoId),peso=Number(carga.qtd||0)*Number(produto?.pesoKg||0),selectedCarga=data.cargas.find(x=>x.id===pedido.cargaId);
 async function salvarVenda(e){e.preventDefault();if(busy)return;setBusy(true);setError('');setMessage('');try{await invoke('CRIAR_VENDA',venda);setVenda({...blankVenda});await listar();setMessage('Pedido de venda salvo e disponível no Forte Vendas para planejamento da carga.');}catch(e){setError(e.message);}finally{setBusy(false)}}
 async function salvarCarga(e){e.preventDefault();if(busy)return;setBusy(true);setError('');setMessage('');try{const r=await invoke('CRIAR_CARGA',carga);setCarga({...blankCarga});const fresh=await listar();const saved=fresh?.cargas?.find(x=>x.id===r.id);setPedido({...blankPedido,cargaId:r.id,fornecedorId:saved?.fornecedorId||carga.fornecedorId});setMessage('Carga salva. Para fazer o pedido ao fornecedor, abra PEDIDOS.');}catch(e){setError(e.message);}finally{setBusy(false)}}
 async function salvarPedido(e){e.preventDefault();if(busy)return;setBusy(true);setError('');setMessage('');try{await invoke('CRIAR_PEDIDO',{id:pedido.cargaId,...pedido});setPedido({...blankPedido});await listar();setMessage('Pedido salvo. Ele está aguardando envio ao fornecedor.');}catch(e){setError(e.message);}finally{setBusy(false)}}
 async function action(acao,id){if(busy)return;setBusy(true);setError('');try{await invoke(acao,{id});await listar();setMessage('Operação registrada.');}catch(e){setError(e.message);}finally{setBusy(false)}}
 return <main>
  <header><div className="brand"><b>FORTE CARGA DIRETA</b><small>CARGAS • PEDIDOS • APROVAÇÕES</small></div><button className="tools-toggle" aria-expanded={showTools} onClick={()=>setShowTools(x=>!x)}>OPÇÕES {showTools?'▴':'▾'}</button><div className="actions" hidden={!showTools}><div data-forte-top-actions aria-label="Ações do sistema"/><button onClick={()=>supabase.auth.signOut()}>SAIR</button></div></header>
  <nav aria-label="Módulos">{[['VENDAS','VENDA AO CLIENTE'],['PEDIDOS','COMPRA AO FORNECEDOR'],['CARGAS','CARGAS'],['APROVACOES','APROVAÇÕES']].map(([id,name])=><button key={id} aria-pressed={tab===id} className={tab===id?'active':''} onClick={()=>{setTab(id);setMessage('')}}>{name}</button>)}</nav>
  <div className="panel-status"><span>{loading?'Carregando cadastros…':`${data.cargas.length} carga(s) • ${data.compras.length} pedido(s)`}</span><button disabled={loading||busy} onClick={listar}>ATUALIZAR</button></div>
  {error&&<section className="feedback error" role="alert">{error}<button disabled={busy||loading} onClick={listar}>TENTAR NOVAMENTE</button></section>}{message&&<p className="feedback success" role="status">{message}</p>}

  {tab==='VENDAS'&&<>
   <form className="card" onSubmit={salvarVenda}><h1>PEDIDO DE VENDA AO CLIENTE</h1><p>Registre os produtos vendidos, o valor e o local de entrega.</p><fieldset disabled={loading||busy}>
    <Select label="CLIENTE" items={data.clientes} value={venda.clienteId} onChange={v=>{const c=data.clientes.find(x=>x.id===v);setVenda(x=>({...x,clienteId:v,destino:c?.cidade||x.destino}))}}/>
    <Select label="VENDEDOR RESPONSÁVEL" items={data.vendedores} value={venda.vendedorId} onChange={v=>patchVenda('vendedorId',v)}/>
    <Select label="PRODUTO" items={data.produtos} value={venda.produtoId} onChange={v=>patchVenda('produtoId',v)} description={x=>`${x.marca||''} • ${x.nome}`}/>
    <div className="form-grid"><label>QUANTIDADE<input required type="number" inputMode="numeric" min="1" step="1" value={venda.qtd} onChange={e=>patchVenda('qtd',e.target.value)}/></label><label>PREÇO DE VENDA UNITÁRIO (R$)<input required type="number" inputMode="decimal" min="0.01" step="0.01" value={venda.precoUnitario} onChange={e=>patchVenda('precoUnitario',e.target.value)}/></label></div>
    <p className="calculation">VALOR DOS PRODUTOS<strong>{money(Number(venda.qtd||0)*Number(venda.precoUnitario||0))}</strong></p>
    <label>CONDIÇÃO DE PAGAMENTO<input required value={venda.condicaoPagamento} onChange={e=>patchVenda('condicaoPagamento',e.target.value)} placeholder="PIX, à vista ou prazo aprovado"/></label><label>ENDEREÇO / LOCAL DE ENTREGA<input required value={venda.destino} onChange={e=>patchVenda('destino',e.target.value)}/></label><label>OBRA / REFERÊNCIA<input value={venda.obra} onChange={e=>patchVenda('obra',e.target.value)}/></label><label>FRETE POR UNIDADE (R$)<input type="number" inputMode="decimal" min="0" step="0.01" value={venda.fretePorSaco} onChange={e=>patchVenda('fretePorSaco',e.target.value)}/></label>
    <label>PALLETS<select required value={venda.pallet} onChange={e=>setVenda(x=>({...x,pallet:e.target.value,palletQuantidade:e.target.value==='SEM PALLETS'?'0':x.palletQuantidade}))}><option value="">SELECIONE…</option><option>COM PALLETS</option><option>SEM PALLETS</option><option>CLIENTE LEVA</option></select></label>{venda.pallet&&venda.pallet!=='SEM PALLETS'&&<label>QUANTIDADE DE PALLETS<input required type="number" min="1" step="1" value={venda.palletQuantidade} onChange={e=>patchVenda('palletQuantidade',e.target.value)}/></label>}<label>OBSERVAÇÕES<textarea value={venda.observacao} onChange={e=>patchVenda('observacao',e.target.value)}/></label><button className="primary" type="submit">{busy?'SALVANDO…':'SALVAR PEDIDO DE VENDA'}</button>
   </fieldset></form><section className="list"><h2>PEDIDOS DE VENDA</h2>{!loading&&!data.vendas.length&&<p className="empty">Nenhum pedido de venda registrado.</p>}{data.vendas.map(x=><article key={x.id}><b>{x.numeroVenda||'PEDIDO DE VENDA'} • {x.cliente}</b><span>{x.produto} • {number(x.qtd)} unidades</span><span>{money(Number(x.qtd||0)*Number(x.precoUnitario||0))} • {x.condicaoPagamento}</span><span>{x.destino}</span><strong>{x.status}</strong></article>)}</section>
  </>}
  {tab==='CARGAS'&&<>
   <form className="card" onSubmit={salvarCarga}><h1>NOVA CARGA</h1><p>Preencha os dados do carregamento para gerar o pedido ao fornecedor.</p><fieldset disabled={loading||busy}>
    <div className="form-grid"><Select label="FORNECEDOR" items={data.fornecedores} value={carga.fornecedorId} onChange={v=>patch('fornecedorId',v)}/><Select label="PRODUTO" items={data.produtos} value={carga.produtoId} onChange={v=>patch('produtoId',v)} description={x=>`${x.marca||''} • ${x.nome}`}/>
    <label>QUANTIDADE ({produto?.unidade||'UNIDADES'})<input required type="number" inputMode="numeric" min="1" step="1" value={carga.qtd} onChange={e=>patch('qtd',e.target.value)}/></label><div className="calculation">PESO TOTAL<strong>{number(peso)} KG • {number(peso/1000)} T</strong></div>
    <Select label="MOTORISTA / VEÍCULO" items={data.motoristasDisponiveis} value={carga.motoristaId} onChange={v=>patch('motoristaId',v)} description={x=>`${x.nome}${x.placa?' • '+x.placa:''}`}/>
    <label>ORIGEM / LOCAL DE CARREGAMENTO<input required value={carga.origem} onChange={e=>patch('origem',e.target.value)} placeholder="Ex.: CSN Arcos/MG"/></label><label>DESTINO / LOCAL DE ENTREGA<input required value={carga.destino} onChange={e=>patch('destino',e.target.value)} placeholder="Cliente, obra ou galpão e cidade"/></label><label>DATA DE CARREGAMENTO<input type="date" value={carga.dataCarregamento} onChange={e=>patch('dataCarregamento',e.target.value)}/></label>
    <label>MODALIDADE DO FRETE<select value={carga.modalidadeFrete} onChange={e=>patch('modalidadeFrete',e.target.value)}><option>FOB</option><option>CIF</option></select></label>{carga.modalidadeFrete==='FOB'&&<label>FRETE POR TONELADA (R$)<input required type="number" inputMode="decimal" min="0" step="0.01" value={carga.fretePorTon} onChange={e=>patch('fretePorTon',e.target.value)}/></label>}
    <label>PALLETS<select required value={carga.pallet} onChange={e=>{patch('pallet',e.target.value);if(e.target.value==='SEM PALLETS')patch('palletQuantidade','0')}}><option value="">SELECIONE…</option><option>COM PALLETS</option><option>SEM PALLETS</option><option>CLIENTE LEVA</option></select></label>{carga.pallet&&carga.pallet!=='SEM PALLETS'&&<label>QUANTIDADE DE PALLETS<input required type="number" inputMode="numeric" min="1" step="1" value={carga.palletQuantidade} onChange={e=>patch('palletQuantidade',e.target.value)}/></label>}
    </div><label>OBSERVAÇÕES<textarea value={carga.observacao} onChange={e=>patch('observacao',e.target.value)}/></label><button className="primary" type="submit">{busy?'SALVANDO…':'SALVAR CARGA'}</button>
   </fieldset></form>
   <section className="list"><h2>CARGAS CADASTRADAS</h2>{!loading&&!data.cargas.length&&<p className="empty">Nenhuma carga ativa. Preencha o formulário acima para cadastrar a primeira.</p>}{data.cargas.map(x=><article key={x.id}><b>{x.codigo}</b><span>{x.produto||x.marca} • {number(x.qtd)} {x.unidade||'UNIDADES'}</span><span>{x.origem||x.localCarregamento||'Origem pendente'} → {x.destino||'Destino pendente'}</span><span>{number(x.pesoKg)} KG • {x.motorista||'Motorista pendente'}</span><strong>{x.fase||x.status}</strong><button onClick={()=>{setPedido({...blankPedido,cargaId:x.id,fornecedorId:x.fornecedorId||''});setTab('PEDIDOS')}}>FAZER PEDIDO DESTA CARGA</button></article>)}</section>
  </>}
  {tab==='PEDIDOS'&&<>
   <form className="card" onSubmit={salvarPedido}><h1>PEDIDO DE COMPRA AO FORNECEDOR</h1><p>Informe o que será comprado. Após salvar, abra o pedido no WhatsApp ou no e-mail do fornecedor.</p><fieldset disabled={loading||busy}>
    <label>VINCULAR A UMA CARGA (OPCIONAL)<select value={pedido.cargaId} onChange={e=>{const c=data.cargas.find(x=>x.id===e.target.value);setPedido(x=>({...x,cargaId:e.target.value,fornecedorId:c?.fornecedorId||x.fornecedorId,produtoId:c?.produtoId||x.produtoId,qtd:c?.qtd||x.qtd,origem:c?.origem||c?.localCarregamento||x.origem,destino:c?.destino||x.destino,pallet:c?.pallet||x.pallet,palletQuantidade:c?.palletQuantidade||x.palletQuantidade}))}}><option value="">PEDIDO SEM CARGA VINCULADA</option>{data.cargas.map(x=><option key={x.id} value={x.id}>{x.codigo} • {x.produto||x.destino}</option>)}</select></label>
    <Select label="FORNECEDOR" items={data.fornecedores} value={pedido.fornecedorId} onChange={v=>{const f=data.fornecedores.find(x=>x.id===v);setPedido(x=>({...x,fornecedorId:v,email:f?.email||'',whatsapp:f?.whatsapp||''}))}}/>
    {!selectedCarga&&<><Select label="PRODUTO" items={data.produtos} value={pedido.produtoId} onChange={v=>patchPedido('produtoId',v)} description={x=>`${x.marca||''} • ${x.nome}`}/><label>QUANTIDADE<input required type="number" inputMode="numeric" min="1" step="1" value={pedido.qtd} onChange={e=>patchPedido('qtd',e.target.value)}/></label></>}
    {selectedCarga&&<p className="calculation">{selectedCarga.produto||selectedCarga.marca} • {number(selectedCarga.qtd)} {selectedCarga.unidade||'UNIDADES'}<br/>{selectedCarga.motorista} • {selectedCarga.pallet||'Pallets pendentes'}</p>}
    <label>PREÇO DE COMPRA UNITÁRIO (R$)<input required type="number" inputMode="decimal" min="0.01" step="0.01" value={pedido.precoCompra} onChange={e=>patchPedido('precoCompra',e.target.value)}/></label><p className="calculation">TOTAL DA COMPRA<strong>{money(Number(selectedCarga?.qtd||pedido.qtd||0)*Number(pedido.precoCompra||0))}</strong></p><label>CONDIÇÃO DE PAGAMENTO<input required value={pedido.condicao} onChange={e=>patchPedido('condicao',e.target.value)}/></label>
    {!selectedCarga&&<><label>ORIGEM / LOCAL DE RETIRADA<input required value={pedido.origem} onChange={e=>patchPedido('origem',e.target.value)}/></label><label>DESTINO / LOCAL DE ENTREGA<input required value={pedido.destino} onChange={e=>patchPedido('destino',e.target.value)}/></label><label>FRETE<select value={pedido.modalidadeFrete} onChange={e=>patchPedido('modalidadeFrete',e.target.value)}><option>FOB</option><option>CIF</option></select></label><label>PALLETS<select required value={pedido.pallet} onChange={e=>setPedido(x=>({...x,pallet:e.target.value,palletQuantidade:e.target.value==='SEM PALLETS'?'0':x.palletQuantidade}))}><option value="">SELECIONE…</option><option>COM PALLETS</option><option>SEM PALLETS</option><option>CLIENTE LEVA</option></select></label>{pedido.pallet&&pedido.pallet!=='SEM PALLETS'&&<label>QUANTIDADE DE PALLETS<input required type="number" min="1" step="1" value={pedido.palletQuantidade} onChange={e=>patchPedido('palletQuantidade',e.target.value)}/></label>}</>}
    <label>WHATSAPP DO FORNECEDOR COM DDD<input type="tel" value={pedido.whatsapp} onChange={e=>patchPedido('whatsapp',e.target.value)} placeholder="Preenchido pelo cadastro; pode corrigir"/></label><label>E-MAIL PARA PEDIDOS<input type="email" value={pedido.email} onChange={e=>patchPedido('email',e.target.value)}/></label><label>OBSERVAÇÕES<textarea value={pedido.observacao} onChange={e=>patchPedido('observacao',e.target.value)}/></label><button className="primary" type="submit">{busy?'SALVANDO…':'SALVAR PEDIDO DE COMPRA'}</button>
   </fieldset></form><section className="list"><h2>PEDIDOS DE COMPRA</h2>{!loading&&!data.compras.length&&<p className="empty">Nenhum pedido registrado. Use o formulário acima.</p>}{data.compras.map(x=><article key={x.id}><b>{x.numero}</b><span>{x.fornecedor}{x.carga?' • '+x.carga:''}</span><span>{x.produto} • {number(x.qtd)} unidades • {money(x.totalCompra)}</span><strong>{x.status}</strong><ContactLinks pedido={x}/></article>)}</section>
  </>}
  {tab==='APROVACOES'&&<section className="list"><h1>APROVAÇÕES</h1><h2>MOTORISTAS</h2>{!loading&&!data.motoristas.length&&<p className="empty">Nenhum motorista aguardando aprovação.</p>}{data.motoristas.map(x=><article key={x.id}><b>{x.nome}</b><span>{x.placas?.join(' / ')||'Placas pendentes'}</span><div><button disabled={busy} onClick={()=>action('APROVAR_MOTORISTA',x.id)}>APROVAR</button><button disabled={busy} className="danger" onClick={()=>action('RECUSAR_MOTORISTA',x.id)}>DEVOLVER</button></div></article>)}<h2>FRETES</h2>{!loading&&!data.fretes.length&&<p className="empty">Nenhum frete aguardando aprovação.</p>}{data.fretes.map(x=><article key={x.id}><b>{x.origem} → {x.destino}</b><span>{number(x.pesoKg)} KG • {money(x.valor)}</span><div><button disabled={busy} onClick={()=>action('APROVAR_FRETE',x.id)}>APROVAR</button><button disabled={busy} className="danger" onClick={()=>action('RECUSAR_FRETE',x.id)}>AJUSTAR</button></div></article>)}</section>}
 </main>;
}
